navikt/pleiepengesoknad-prosessering

src/main/kotlin/no/nav/helse/prosessering/v1/PreprosseseringV1Service.kt

Handles eventual failed child-name lookup, and returns null.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt

Overrides toString in data classes to hide potential sensitive data.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt

BR-70 lagt til oppdrag til pdf sander

---

src/main/resources/handlebars/partials/checkbox_partial.hbs
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt

og brukt det for frilans og samtykke i pdf

BR-70 Lagd handlebars partial for checkbox

---

.github/workflows/build-and-deploy.yml
kafka/oneshot.json

Fjerne prosessering som consumer av journalført og slette oppgaveOpprettet-topics bør gjøres som en egen operasjon etter at ansvaret er flyttet til k9-fordel

Lagt til kafka-topic for cleanup

---

nais/alerterator.yml

Øker tiden for "Applikasjon nede" alert fra 2min til 10min.
Øker tiden for varsling av streams fra 1min, til 20 min.

Utvider tiden før alarmer

---

src/main/kotlin/no/nav/helse/k9format/K9Format.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprosseseringV1Service.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/PleiepengesoknadProsesseringTest.kt
src/test/kotlin/no/nav/helse/k9format/JournalføringKafkaFormat.kt
src/test/kotlin/no/nav/helse/k9format/MedlemskapTest.kt

* Fjerner optional på UtenlandsoppholdIPerioden, da den aldri er null.
* Utvider assertJournalførtFormat med støtte for å printe k9Format json.

Bygger bosteder og utenlandsopphold dersom de eksisterer.

---

.github/workflows/apply-alerts.yml
.github/workflows/build-and-deploy.yml
nais/dev-fss.json

Oppdaterer checkout og cache.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

Utvider metrics med hvor mange som har arbeidsaktivitetet:
arbeidstaker
arbeidstaker og frilanser
arbeidstaker og selvstendig
arbeidstaker, frilanser og selvstendig
frilanser og selvstendig
frilanser
selvstendig
Hvor mange som velger de ulike valgene på arbeid:
nei, skal ikke jobbe
Ja, skal jobbe som normalt
skal jobbe mindre enn normalt
vet ikke
Alternativer

Legger til metrics.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt

Dersom søker ikke har valgt arbeidsgiver, frilanser eller selvstendigVirksomhet

Legger til counter for ingen inntekt.

---

src/main/kotlin/no/nav/helse/felles/Felles.kt
src/main/kotlin/no/nav/helse/felles/Virksomhet.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt

Flytter Virksomhet og tilhørende klasser til egen fil for bedre lesbarhet og oversikt.
Hjelpemetode slik at pdf ikke blir berørt før frontend og api er oppdatert. 
Endrer rekkefølge og oppsett på PDF om selvstendig næringsdrivende

Legger til nytt felt; flereAktiveVirksomheter

---

.github/workflows/build-and-deploy.yml
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Closes #102
Closes #101
Closes #98
Closes #94
Closes #89
Closes #86

Oppdaterer avhengigheter.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/soknad.hbs

Sjekker om feltet er satt før vi legger det til i pdf

Setter verneplikt som optional.

---

src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/soknad.hbs
src/main/resources/handlebars/style-common.hbs

Endrer på oppsett for arbeidstimer på PDF for arbeidstaker, frilanser og selvstendig næringsdrivenede.

---

nais/dev-fss.json
nais/naiserator.yml
nais/prod-fss.json
src/main/kotlin/no/nav/helse/auth/AccessTokenClientResolver.kt
src/main/resources/application.conf

Ga denne feilen i prod:
Feil ved 'JournalforingV1'. IllegalStateException med melding 'Feil ved henting av access token = '{"error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=501051"}''

Ruller tilbake AzureAD endring.

---

nais/dev-fss.json
nais/prod-fss.json
src/main/kotlin/no/nav/helse/auth/AccessTokenClientResolver.kt
src/main/resources/application.conf

Bruker azurator ad client

---

build.gradle.kts
src/main/kotlin/no/nav/helse/Configuration.kt
src/main/kotlin/no/nav/helse/PleiepengesoknadProsessering.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt

Konfigurerer tester til å kjøre på junit5 med org.jetbrains.kotlin:kotlin-test-junit5.
- closes #106
- closes #109
- closes #118

Oppdaterer pakker og fjerner/refaktorere deprekerte metoder.

---

src/main/kotlin/no/nav/helse/kafka/Topology.kt
src/main/kotlin/no/nav/helse/prosessering/Metadata.kt
src/test/kotlin/no/nav/helse/KafkaWrapper.kt
src/test/kotlin/no/nav/helse/MetadataTest.kt

Fjerner requestId da det ikke brukes til noe.

---

src/main/kotlin/no/nav/helse/felles/Felles.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt

Samt, fjernes det gamle formatet for omsorgstilbud.

Legger til metrikker for søknadsperidode.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1Metrics.kt

Fjerner unødvendige metrikker.

---

src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt

Legger til sluttetFørSøknadsperiode som felt og i pdf.

---

src/main/kotlin/no/nav/helse/felles/Arbeid.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprosseseringV1Service.kt
src/main/resources/handlebars/partial/arbeidIPeriodePartial.hbs
src/main/resources/handlebars/partial/arbeidsforholdPartial.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

- Viser info om jobbeProsent dersom det jobbes redusert.
- Refaktorer arbeidIPerioden partial til å ta høyde for historisk og planlagt arbeid.

Legger til støtte for jobberProsent ved redusert arbeid.

---

src/main/kotlin/no/nav/helse/felles/Arbeid.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PdfV1Generator.kt
src/main/resources/handlebars/partial/arbeidIPeriodePartial.hbs
src/test/kotlin/no/nav/helse/PdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

- Fjerner jobberSomVanlig.
- Fjerner VET_IKKE som svar alternativ i jobber i perioden.
- Fjerner alternativ svar på pdf ang. jobber som vanlig.

Refaktorerer ArbeidIPeriode.

---

.github/workflows/build-and-deploy.yml
build.gradle.kts
src/test/kotlin/no/nav/helse/SøknadUtils.kt

- Refaktorerer utgåtte builders og konsutruktører på k9-format.
- closes #168
- closes #167
- closes #166
- closes #159
- closes #154

Oppdaterer dusseldorf-ktor, plugins, pakker og actions.

---

src/main/kotlin/no/nav/helse/felles/Arbeid.kt
src/main/kotlin/no/nav/helse/felles/Omsorgstilbud.kt
src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt
src/main/resources/handlebars/partial/arbeidIPeriodePartial.hbs
src/main/resources/handlebars/partial/arbeidsforholdPartial.hbs
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/PleiepengesoknadProsesseringTest.kt
src/test/kotlin/no/nav/helse/SøknadPdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

Oppdaterer pdf.
Fjerner todo som ikke er gjeldene, feltene skal være nullable

Fjerner fortid/fremtid for omsorgstilbud og arbeidsforhold

---

src/main/kotlin/no/nav/helse/felles/Felles.kt
src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1Metrics.kt
src/main/kotlin/no/nav/helse/utils/MetricUtils.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/BarnTest.kt
src/test/kotlin/no/nav/helse/SøknadPdfV1GeneratorTest.kt

Legger til fødsesldato og årsak -> mapper opp til pdf

Støtter barn uten identitetsnummer.

---

src/main/kotlin/no/nav/helse/felles/Arbeid.kt
src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1.kt
src/main/resources/handlebars/partial/arbeidsforholdPartial.hbs
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/SøknadPdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

Delt opp det som hører til arbeidssituasjon og arbeid i perioden på pdf. Matcher mer oppsummeringen

Refaktorering arbeid

---

.github/workflows/apply-alerts.yml
.github/workflows/build-and-deploy.yml
.github/workflows/deploy-kafka.yml
.github/workflows/snyk.yml
build.gradle.kts

* Closes #197
* Closes #192
* Closes #191
* Closes #177

Oppdaterer pakker og actions.

---

.github/workflows/build-and-deploy.yml
build.gradle.kts

Oppdaterer k9Format og actions.

---

Dockerfile

Erstatter navikt/java:17 med distroless/java17

---

src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt
src/main/kotlin/no/nav/helse/prosessering/v1/MeldingV1.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprosseseringV1Service.kt
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/SøknadPdfV1GeneratorTest.kt
src/test/kotlin/no/nav/helse/SøknadUtils.kt

Støtter opplasting av fødselsattest ved manglende fnr på barn.

---

src/main/kotlin/no/nav/helse/felles/Arbeid.kt
src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt
src/main/resources/handlebars/partial/arbeid/arbeidIPeriode/arbeiderEnkeltdagerPartial.hbs
src/main/resources/handlebars/partial/arbeid/arbeidIPeriode/arbeiderFasteUkedagerPartial.hbs
src/main/resources/handlebars/partial/arbeid/arbeidIPeriode/arbeidsukerPartial.hbs
src/main/resources/handlebars/partial/arbeid/arbeidsforholdPartial.hbs
src/main/resources/handlebars/soknad.hbs
src/test/kotlin/no/nav/helse/SøknadPdfV1GeneratorTest.kt

Mapper på arbeidsuker på søknads-PDF.

---

src/main/kotlin/no/nav/helse/pdf/SøknadPDFGenerator.kt

Locale.getDefault() returnerer inkrementert uketall.

Fikser uketall.

---

.github/workflows/build-and-deploy.yml
build.gradle.kts
src/main/kotlin/no/nav/helse/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/helse/prosessering/v1/PreprossesertMeldingV1Metrics.kt
src/test/kotlin/no/nav/helse/EndringsmeldingUtils.kt
src/test/kotlin/no/nav/helse/KafkaWrapper.kt
src/test/kotlin/no/nav/helse/PleiepengesoknadProsesseringTest.kt
src/test/kotlin/no/nav/helse/PleiepengesoknadProsesseringWithMocks.kt
src/test/kotlin/no/nav/helse/TestConfiguration.kt

- Oppgraderer pakker og plugins.

Erstatter kafkaEmbeddedEnv med testcontainers.
